--- # Config file for Wiki API Connector ingest. Make sure there are no TAB characters in this YAML file!
units:
    - unit:
        name: Smithsonian National Museum of Natural History
#            id_pattern: "^nmnhbotany_[0-9.]+"
        api:
            api_url: https://api.si.edu/openaccess/api/v1.0/content/edanmdm:{}?api_key={}
            api_key: true
            api_key_info: https://api.data.gov/signup/
            api_key_string: SECRET
            fields: [identifier, api_key_string]
        generic:
            permission: 
                jsonpath: $.response.content.descriptiveNonRepeating.metadata_usage.access
                values: [CC0]
            edit_summary: "Uploaded with Wiki API Connector"
            max_title_length: 96
        commons_template: 
#            url: https://commons.wikimedia.org/wiki/Template:Information
            type: Information
            selector_path: [jsonpath, static, append]
            crosswalk: # Hard mappings
                permission:
                    CC0: "{{CC-zero}}"
                category: # TODO: Need to implement this
                    object type:
                        Specimen: Specimen in the Smithsonian NMNH
            categories: "[[Category:Collections of the National Museum of Natural History, United States]]"
            append: "{{Uploaded with Wiki API Connector}}" # Append to all uploads, template or otherwise
            commons_filename_format: "title, identifier, basefilename"
            fields:
                _image:
                    jsonpath: $.response.content.descriptiveNonRepeating.online_media.media[*].resources[?(@.label == 'High-resolution JPEG')].url
                title: 
                    jsonpath: $.response.title
                description:
                    jsonpath: "'Smithsonian '+$.response.content.freetext.dataSource[?(@.label == 'Data Source')].content+'\n\nName: '+$.response.title+'\n\nTaxonomy: '+$.response.content.freetext.taxonomicName[?(@.label == 'Taxonomy')].content+'\n\nPlace: '+$.response.content.freetext.place[?(@.label == 'Place')].content+'\n\nBarcode: '+$.response.content.freetext.identifier[?(@.label == 'Barcode')].content+'\n\nUSNM Number: '+$.response.content.freetext.identifier[?(@.label == 'USNM Number')].content+'\n\nCollection date: '+$.response.content.freetext.date[?(@.label == 'Collection Date')].content+'\n\nSmithsonian record ID: '+$.response.content.descriptiveNonRepeating.record_ID+'\n\nRecord link: '+'https://collections.si.edu/search/detail/'+$.response.url"
                date:
                    jsonpath: $.response.content.freetext.date[?(@.label == 'Collection Date')].content
                author: 
                    static: "{{Institution:National Museum of Natural History, United States}}"
                source: 
                    jsonpath: $.response.content.descriptiveNonRepeating.record_link
                    append: "{{Smithsonian}}"
                permission:
                    jsonpath: $.response.content.descriptiveNonRepeating.online_media.media[*].usage.access
        commons_wikibase:
            selector_path: [jsonpath, static] # And append
            statements:  # TODO: maybe change this to fields to be consistent with above
                P4765: # Commons compatible at URL
                    jsonpath: $.response.content.descriptiveNonRepeating.online_media.media[*].resources[?(@.label == 'High-resolution JPEG')].url
                P275:
                    static: Q6938433 # CC0 copyright license
                    entity-type: item
                P6216:
                    static: Q88088423 # dedicated to the public domain by copyright holder
                    entity-type: item
                P4704:  # object number, takes URL then finds substrings after ? and =
                    jsonpath: $.response.content.descriptiveNonRepeating.record_link.`split(?, 1, -1)`.`split(=, 1, -1)`
                P7851:
                    jsonpath: $.response.content.descriptiveNonRepeating.record_ID # Smithsonian resource ID
                P9473:
                    jsonpath: $.response.content.descriptiveNonRepeating.guid.`split(/, 5, -1)` # Smithsonian ARK ID
    - unit:
        name: Smithsonian American Art Museum
#            id_pattern: "^saam_[0-9.]+"
        api:
            api_url: https://api.si.edu/openaccess/api/v1.0/content/edanmdm:{}?api_key={}
            api_key: true
            api_key_info: https://api.data.gov/signup/
            api_key_string: SECRET
            fields: [identifier, api_key_string]
        generic:
            permission: 
                jsonpath: $.response.content.descriptiveNonRepeating.metadata_usage.access
                values: [CC0]
            edit_summary: "Uploaded with Wiki API Connector"
            max_title_length: 96
        commons_template: 
#            url: https://commons.wikimedia.org/wiki/Template:Artwork
            type: Artwork
            selector_path: [jsonpath, static, append]
            crosswalk: # Hard mappings
                permission:
                    CC0: "{{CC-zero}}"
                category: # TODO: Need to implement this
                    object type:
                        Paintings: Paintings in the Smithsonian American Art Museum
                        Sculpture (visual work): Sculptures in the Smithsonian American Art Museum
            categories: "[[Category:Collections of the Smithsonian American Art Museum]] [[Category:Military in the Smithsonian American Art Museum]]"
            append: "{{Uploaded with Wiki API Connector}}" # Append to all uploads, template or otherwise
            commons_filename_format: "title, basefilename"
            fields:
                _image:
                    jsonpath: $.response.content.descriptiveNonRepeating.online_media.media[*].resources[?(@.label == 'High-resolution JPEG')].url
                title: 
                    jsonpath: $.response.title
#                    formatstring: "{{en|%s}}"
                accession number: 
                    jsonpath: $.response.content.freetext.identifier[?(@.label == 'Object number')].content
                artist: 
                    jsonpath: $.response.content.indexedStructured.name[*]
                    action: reconcile
                object type: 
                    jsonpath: $.response.content.indexedStructured.object_type[*]
                description:
                    jsonpath: "$.response.content.freetext.dataSource[?(@.label == 'Data Source')].content+'\n\nName: '+$.response.title+'\n\nDimensions: '+$.response.content.freetext.physicalDescription[?(@.label == 'Dimensions')].content+'\n\nSmithsonian record ID: '+$.response.content.descriptiveNonRepeating.record_ID+'\n\nRecord link: '+'https://collections.si.edu/search/detail/'+$.response.url"
                date:
                    jsonpath: $.response.content.freetext.date[?(@.label == 'Date')].content
                medium: 
                    jsonpath: $.response.content.freetext.physicalDescription[?(@.label == 'Medium')].content
                dimensions: 
                    jsonpath: $.response.content.freetext.physicalDescription[?(@.label == 'Dimensions')].content
                institution: 
                    static: "{{Institution:Smithsonian American Art Museum}}"
                department:
                    jsonpath: $.response.content.freetext.setName[?(@.label == 'Department')].content
                credit line:
                    jsonpath: $.response.content.freetext.creditLine[?(@.label == 'Credit Line')].content
                source: 
                    jsonpath: $.response.content.descriptiveNonRepeating.record_link+" <br> "+$.response.content.descriptiveNonRepeating.guid
                    append: "{{SAAM-cooperation}} {{Smithsonian}}"
                permission:
                    jsonpath: $.response.content.descriptiveNonRepeating.online_media.media[*].usage.access
        commons_wikibase:
            selector_path: [jsonpath, static] # And append
            statements:  # TODO: maybe change this to fields to be consistent with above
                P4765: # Commons compatible at URL
                    jsonpath: $.response.content.descriptiveNonRepeating.online_media.media[*].resources[?(@.label == 'High-resolution JPEG')].url
                P275:
                    static: Q6938433 # CC0 copyright license
                    entity-type: item
                P6216:
                    static: Q88088423 # dedicated to the public domain by copyright holder
                    entity-type: item
                P4704:  # SAAM object number, takes URL then finds substrings after ? and =
                    jsonpath: $.response.content.descriptiveNonRepeating.record_link.`split(?, 1, -1)`.`split(=, 1, -1)`
                P7851:
                    jsonpath: $.response.content.descriptiveNonRepeating.record_ID # Smithsonian resource ID
                P9473:
                    jsonpath: $.response.content.descriptiveNonRepeating.guid.`split(/, 5, -1)` # Smithsonian ARK ID
